Added open graph image for linkedin
EtchUK/Etch.OrchardCore.SEO pull request #69
Opened 2021-03-02 15:35 UTC by devlife

LinkedIn uses open graph image meta tags like this: `<meta name="image" property="og:image" content="{path} />` as can be seen in the [post inspector](https://www.linkedin.com/post-inspector/).

Happy to make any additional changes or follow a different approach.

2021-03-02 15:36 UTC, devlife commented on MetaTags/Models/MetaTagsPart.cs
> -﻿using OrchardCore.ContentManagement;
These changes were from line endings. I can undo if requested.

2021-03-02 16:03 UTC, peterkeating commented on Etch.OrchardCore.SEO.csproj
> +    <Version>0.7.1-rc2</Version>
You'll also need to change the version number in the [`Manifest.cs`](https://github.com/EtchUK/Etch.OrchardCore.SEO/blob/master/Manifest.cs#L7) file.

2021-03-02 16:03 UTC, peterkeating commented on MetaTags/Services/MetaTagsService.cs
> +using Etch.OrchardCore.Fields.Eventbrite.Models.Dto;
Don't think you meant to add this reference?

2021-03-03 18:21 UTC, peterkeating requested changes

2021-03-03 18:21 UTC, peterkeating commented on Manifest.cs
> +    Version = "0.7.1-rc2"
Sorry the "rc2" postfix isn't needed.

2021-03-04 00:39 UTC, devlife commented
Removed `-rc2`

2021-03-04 08:31 UTC, merged